/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.feistapps.contentresolver;

import android.app.Activity;
import android.content.Context;
import android.content.ContentResolver;
import android.database.Cursor;
import android.net.Uri;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

@Kroll.module(name="Contentresolver", id="com.feistapps.contentresolver")
public class ContentresolverModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "ContentresolverModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public ContentresolverModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public String resolveURL()
	{
		Activity activity = getActivity();
		String filePath = null;
		Uri url = activity.getIntent().getData();
		if (url != null && "content".equals(url.getScheme())) {
			ContentResolver resolver = activity.getContentResolver();
	        Cursor cursor = resolver.query(url, new String[] { android.provider.MediaStore.Images.ImageColumns.DATA }, null, null, null);
	        cursor.moveToFirst();   
	        filePath = cursor.getString(0);
	        cursor.close();
	    }
		if(url==null) {
			return null;
		} else if(filePath==null) {
			return url.getPath();
		}
	    return filePath;
	}
	
	// Properties
	/*@Kroll.getProperty
	public String getExampleProp()
	{
		Log.d(TAG, "get example property");
		return "hello world";
	}
	
	
	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(TAG, "set example property: " + value);
	}*/

}

